services:
    dittto_custom_request.requests:
        class: Dittto\CustomRequestBundle\Request\RequestParameterConverter
        arguments: ['@service_container']
        tags:
            - {name: request.param_converter, converter: dittto_custom_requests}

    dittto.request.exception_on_failed_get:
        class: Dittto\CustomRequestBundle\Request\Filter\ExceptionOnFailedGetRequest
        tags: [ { name: dittto.request_filter, slot: 10 } ]
